[[collection]]
type="box"
img="/assets/box-1.jpg"
link="https://example.com"
rotate=true
title="Reze"
subtitle="Let’s run away together"

[[collection]]
type="box"
img="/assets/box-2.jpg"
link="https://example.com"
rotate=true
title="Kobeni Higashiyama"
subtitle="I-I just want to survive..."

[[collection]]
type="box"
img="/assets/box-3.jpg"
link="https://example.com"
rotate=true
title="Power"
subtitle="Bow before me, humans!"

[[collection]]
type="box"
img="/assets/box-4.jpg"
link="https://example.com"
rotate=true
title="Denji"
subtitle="I want to live a normal life, eat good food, and maybe touch some boobs"

[[collection]]
type="box"
img="/assets/box-9.jpg"
link="https://example.com"
rotate=true
title="Kishibe"
subtitle="The stronger you are, the more you lose"

[[collection]]
type="box"
img="/assets/box-6.jpg"
link="https://example.com"
rotate=true
title="Himeno"
subtitle="I’ll protect you, even if it costs me my life"

[[collection]]
type="box"
img="/assets/box-7.jpg"
link="https://example.com"
rotate=true
title="Yoru"
subtitle="I am the War Devil. I will make humans fear war again"

[[collection]]
type="box"
img="/assets/box-13.jpg"
link="https://example.com"
rotate=true
title="Pochita"
subtitle="Take care of Denji for me"

[[collection]]
type="box"
img="/assets/box-5.jpg"
link="https://example.com"
rotate=true
title="Aki Hayakawa"
subtitle="I will kill the Gun Devil, no matter what it takes"

[[collection]]
type="box"
img="/assets/box-12.jpg"
link="https://example.com"
rotate=true
title="Makima"
subtitle="You are my dog, Denji. You belong to me"
