[[collection]]
type = "card"
title = "Tokio"
link = "https://example.com"
content = "Tokio is an asynchronous runtime for the Rust programming language. It provides the building blocks needed for writing network applications. It gives the flexibility to target a wide range of systems, from large servers with dozens of cores to small embedded devices."
tags = ["rust", "async", "runtime"]

[[collection]]
type = "card"
title = "Kubernetes"
link = "https://example.com"
content = "Kubernetes, also known as K8s, is an open source system for managing containerized applications across multiple hosts. It provides basic mechanisms for the deployment, maintenance, and scaling of applications."
tags = ["k8s", "golang"]

[[collection]]
type = "card"
title = "Next.js"
link = "https://example.com"
content = "Next.js is a React framework for building full-stack web applications. You use React Components to build user interfaces, and Next.js for additional features and optimizations."
tags = ["typescript", "react", "frontend"]
